// Autogenerated c file for coll bank inclusion

#include "levbanks\collext.h"

unsigned long numLevels = 4;

char *collBanksStart[4] =
{
	_collBank000SegmentRomStart,
	_collBank001SegmentRomStart,
	_collBank002SegmentRomStart,
	_collBank003SegmentRomStart,
};

char *collBanksEnd[4] =
{
	_collBank000SegmentRomEnd,
	_collBank001SegmentRomEnd,
	_collBank002SegmentRomEnd,
	_collBank003SegmentRomEnd,
};
