// Autogenerated c file for coll bank inclusion

#include "levbanks\levext.h"

unsigned long numLevels = 0;
char levelNames[0][32] = 
{
};

char **collBanksStart[0] =
{
};

char **collBanksEnd[0] =
{
};

char **scenBanksStart[0] =
{
};

char **scenBanksEnd[0] =
{
};
