// Autogenerated c file for coll bank inclusion

#include "levbanks\levext.h"

unsigned long numLevels = 10;
char levelNames[10][32] = 
{
	"vegpatch",
	"lawn",
	"cstreets",
	"docksa",
	"maze",
	"retro1",
	"warehouse",
	"citymulti",
	"citybon",
	"gardenmulti",
};

char **collBanksStart[10] =
{
	&_collBank000SegmentRomStart,
	&_collBank001SegmentRomStart,
	&_collBank002SegmentRomStart,
	&_collBank003SegmentRomStart,
	&_collBank004SegmentRomStart,
	&_collBank005SegmentRomStart,
	&_collBank006SegmentRomStart,
	&_collBank007SegmentRomStart,
	&_collBank008SegmentRomStart,
	&_collBank009SegmentRomStart,
};

char **collBanksEnd[10] =
{
	&_collBank000SegmentRomEnd,
	&_collBank001SegmentRomEnd,
	&_collBank002SegmentRomEnd,
	&_collBank003SegmentRomEnd,
	&_collBank004SegmentRomEnd,
	&_collBank005SegmentRomEnd,
	&_collBank006SegmentRomEnd,
	&_collBank007SegmentRomEnd,
	&_collBank008SegmentRomEnd,
	&_collBank009SegmentRomEnd,
};

char **scenBanksStart[10] =
{
	&_scenBank000SegmentRomStart,
	&_scenBank001SegmentRomStart,
	&_scenBank002SegmentRomStart,
	&_scenBank003SegmentRomStart,
	&_scenBank004SegmentRomStart,
	&_scenBank005SegmentRomStart,
	&_scenBank006SegmentRomStart,
	&_scenBank007SegmentRomStart,
	&_scenBank008SegmentRomStart,
	&_scenBank009SegmentRomStart,
};

char **scenBanksEnd[10] =
{
	&_scenBank000SegmentRomEnd,
	&_scenBank001SegmentRomEnd,
	&_scenBank002SegmentRomEnd,
	&_scenBank003SegmentRomEnd,
	&_scenBank004SegmentRomEnd,
	&_scenBank005SegmentRomEnd,
	&_scenBank006SegmentRomEnd,
	&_scenBank007SegmentRomEnd,
	&_scenBank008SegmentRomEnd,
	&_scenBank009SegmentRomEnd,
};
