// Autogenerated header for coll bank inclusion

#ifndef COLLEXT_H_INCLUDED
#define COLLEXT_H_INCLUDED

enum
{
	NUM_COLL_BANK
};

extern unsigned long numLevels;
extern char levelNames[0][32];

extern char **collBanksStart[0];
extern char **collBanksEnd[0];

extern char **scenBanksStart[0];
extern char **scenBanksEnd[0];



#endif
