// Autogenerated header for coll bank inclusion

#ifndef COLLEXT_H_INCLUDED
#define COLLEXT_H_INCLUDED

enum
{
	VEGPATCH_COLL_BANK,
	LAWN_COLL_BANK,
	CSTREETS_COLL_BANK,
	DOCKSA_COLL_BANK,
	MAZE_COLL_BANK,
	RETRO1_COLL_BANK,
	WAREHOUSE_COLL_BANK,
	CITYMULTI_COLL_BANK,
	CITYBON_COLL_BANK,
	GARDENMULTI_COLL_BANK,
	NUM_COLL_BANK
};

extern unsigned long numLevels;
extern char levelNames[10][32];

extern char **collBanksStart[10];
extern char **collBanksEnd[10];

extern char **scenBanksStart[10];
extern char **scenBanksEnd[10];

extern char *_collBank000SegmentRomStart;
extern char *_collBank000SegmentRomEnd;
extern char *_collBank001SegmentRomStart;
extern char *_collBank001SegmentRomEnd;
extern char *_collBank002SegmentRomStart;
extern char *_collBank002SegmentRomEnd;
extern char *_collBank003SegmentRomStart;
extern char *_collBank003SegmentRomEnd;
extern char *_collBank004SegmentRomStart;
extern char *_collBank004SegmentRomEnd;
extern char *_collBank005SegmentRomStart;
extern char *_collBank005SegmentRomEnd;
extern char *_collBank006SegmentRomStart;
extern char *_collBank006SegmentRomEnd;
extern char *_collBank007SegmentRomStart;
extern char *_collBank007SegmentRomEnd;
extern char *_collBank008SegmentRomStart;
extern char *_collBank008SegmentRomEnd;
extern char *_collBank009SegmentRomStart;
extern char *_collBank009SegmentRomEnd;

extern char *_scenBank000SegmentRomStart;
extern char *_scenBank000SegmentRomEnd;
extern char *_scenBank001SegmentRomStart;
extern char *_scenBank001SegmentRomEnd;
extern char *_scenBank002SegmentRomStart;
extern char *_scenBank002SegmentRomEnd;
extern char *_scenBank003SegmentRomStart;
extern char *_scenBank003SegmentRomEnd;
extern char *_scenBank004SegmentRomStart;
extern char *_scenBank004SegmentRomEnd;
extern char *_scenBank005SegmentRomStart;
extern char *_scenBank005SegmentRomEnd;
extern char *_scenBank006SegmentRomStart;
extern char *_scenBank006SegmentRomEnd;
extern char *_scenBank007SegmentRomStart;
extern char *_scenBank007SegmentRomEnd;
extern char *_scenBank008SegmentRomStart;
extern char *_scenBank008SegmentRomEnd;
extern char *_scenBank009SegmentRomStart;
extern char *_scenBank009SegmentRomEnd;

#endif
